import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialDatabaseSetup1754728311188 implements MigrationInterface {
    name = 'InitialDatabaseSetup1754728311188'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tbl_user_profiles" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "date_of_birth" date, "gender" character varying(10), "address" text, "emergency_contact" jsonb, "bio" text, "social_links" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5d9c02e75b2b8b22c9708ae5590" UNIQUE ("user_id"), CONSTRAINT "REL_5d9c02e75b2b8b22c9708ae559" UNIQUE ("user_id"), CONSTRAINT "PK_2b9768a0f3333f4326f9062352b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tbl_players" ("id" SERIAL NOT NULL, "user_id" integer, "player_code" character varying(20), "full_name" character varying(255) NOT NULL, "gender" character varying(10) NOT NULL, "date_of_birth" date, "height" integer, "weight" integer, "dominant_hand" character varying(15), "jersey_number" integer, "primary_position" character varying(30), "secondary_positions" text array, "skill_level" character varying(20) NOT NULL DEFAULT 'beginner', "contact_info" jsonb, "avatar_url" character varying(500), "action_photos" text array, "status" character varying(20) NOT NULL DEFAULT 'active', "injury_details" text, "medical_notes" text, "join_date" date NOT NULL DEFAULT ('now'::text)::date, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cf55e3017ab32f2dbf438e0b3dc" UNIQUE ("user_id"), CONSTRAINT "UQ_d505b968f838bbb3e6230caf564" UNIQUE ("player_code"), CONSTRAINT "REL_cf55e3017ab32f2dbf438e0b3d" UNIQUE ("user_id"), CONSTRAINT "PK_cf2cf9267f3a36ef92b4c5ed747" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf55e3017ab32f2dbf438e0b3d" ON "tbl_players" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9dae2eefae9e71064fa8fe1ba3" ON "tbl_players" ("full_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_d505b968f838bbb3e6230caf56" ON "tbl_players" ("player_code") `);
        await queryRunner.query(`CREATE TABLE "tbl_users" ("id" SERIAL NOT NULL, "username" character varying(50) NOT NULL, "email" character varying(100) NOT NULL, "password_hash" character varying(255) NOT NULL, "first_name" character varying(100), "last_name" character varying(100), "phone" character varying(20), "avatar_url" character varying(500), "role" character varying(20) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_login" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_22e9c745c648bad6b39c5d5b58e" UNIQUE ("username"), CONSTRAINT "UQ_d74ab662f9d3964f78b3416d5da" UNIQUE ("email"), CONSTRAINT "PK_bb1d884179b3e42514b36c01e4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d74ab662f9d3964f78b3416d5d" ON "tbl_users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_22e9c745c648bad6b39c5d5b58" ON "tbl_users" ("username") `);
        await queryRunner.query(`CREATE TABLE "tbl_divisions" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "description" text, "level" character varying(20) NOT NULL, "age_group" character varying(20), "gender_category" character varying(20), "max_teams" integer, "season_start" date, "season_end" date, "registration_fee" numeric(10,2), "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d8003b55efcb85e34f9f06bcdb8" UNIQUE ("code"), CONSTRAINT "PK_c67a10eb84f5fce66df908acb08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8003b55efcb85e34f9f06bcdb" ON "tbl_divisions" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_ee1c4de334a95fc856c0daf615" ON "tbl_divisions" ("name") `);
        await queryRunner.query(`CREATE TABLE "tbl_teams" ("id" SERIAL NOT NULL, "division_id" integer NOT NULL, "name" character varying(100) NOT NULL, "short_name" character varying(10), "code" character varying(20) NOT NULL, "level" integer NOT NULL, "description" text, "max_members" integer NOT NULL DEFAULT '18', "coach_id" integer, "assistant_coach_id" integer, "team_logo_url" character varying(500), "team_color" character varying(7), "secondary_color" character varying(7), "founded_date" date, "home_venue" character varying(200), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b40662ac94791561ce5f411e062" UNIQUE ("code"), CONSTRAINT "PK_f67d422c12ccdbc2eaa59be89ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b40662ac94791561ce5f411e06" ON "tbl_teams" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb2b45887926dddc95622d8376" ON "tbl_teams" ("division_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aac77fb1de4d7063c45934d922" ON "tbl_teams" ("name") `);
        await queryRunner.query(`CREATE TABLE "tbl_team_stats" ("id" SERIAL NOT NULL, "team_id" integer NOT NULL, "season" character varying(20) NOT NULL, "tournament" character varying(50), "matches_played" integer NOT NULL DEFAULT '0', "matches_won" integer NOT NULL DEFAULT '0', "matches_lost" integer NOT NULL DEFAULT '0', "sets_won" integer NOT NULL DEFAULT '0', "sets_lost" integer NOT NULL DEFAULT '0', "points_for" integer NOT NULL DEFAULT '0', "points_against" integer NOT NULL DEFAULT '0', "win_percentage" numeric(5,2) NOT NULL DEFAULT '0', "current_streak" integer NOT NULL DEFAULT '0', "longest_win_streak" integer NOT NULL DEFAULT '0', "ranking_position" integer, "total_aces" integer NOT NULL DEFAULT '0', "total_blocks" integer NOT NULL DEFAULT '0', "total_kills" integer NOT NULL DEFAULT '0', "is_current_season" boolean NOT NULL DEFAULT true, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_094d57b5c12940875f476865195" UNIQUE ("team_id", "season", "tournament"), CONSTRAINT "PK_d35900b876281c176d28f8bc9f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_62a6114da9c78a55fc620da2c1" ON "tbl_team_stats" ("season") `);
        await queryRunner.query(`CREATE INDEX "IDX_fee0b5954caea0f19ad63ef24d" ON "tbl_team_stats" ("team_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_team_members" ("id" SERIAL NOT NULL, "team_id" integer NOT NULL, "player_id" integer NOT NULL, "jersey_number" integer, "position" character varying(30), "is_captain" boolean NOT NULL DEFAULT false, "is_vice_captain" boolean NOT NULL DEFAULT false, "is_starting_lineup" boolean NOT NULL DEFAULT false, "status" character varying(20) NOT NULL DEFAULT 'active', "joined_date" date NOT NULL DEFAULT ('now'::text)::date, "left_date" date, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_be5f97410861dabc223f168fe81" UNIQUE ("team_id", "jersey_number"), CONSTRAINT "UQ_7ebb6184866b591afed82baa186" UNIQUE ("team_id", "player_id"), CONSTRAINT "PK_fa6ee45f2eb61328a6aa12902a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1689d4b0d6dcbc5ae5fe2413c9" ON "tbl_team_members" ("player_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_faead59db8023099d9d0046249" ON "tbl_team_members" ("team_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_player_statistics" ("id" SERIAL NOT NULL, "player_id" integer NOT NULL, "season" character varying(20) NOT NULL, "tournament" character varying(50), "matches_played" integer NOT NULL DEFAULT '0', "total_points" integer NOT NULL DEFAULT '0', "serves_attempted" integer NOT NULL DEFAULT '0', "serves_successful" integer NOT NULL DEFAULT '0', "aces" integer NOT NULL DEFAULT '0', "service_errors" integer NOT NULL DEFAULT '0', "attacks_attempted" integer NOT NULL DEFAULT '0', "attacks_successful" integer NOT NULL DEFAULT '0', "kills" integer NOT NULL DEFAULT '0', "attack_errors" integer NOT NULL DEFAULT '0', "blocks_solo" integer NOT NULL DEFAULT '0', "blocks_assisted" integer NOT NULL DEFAULT '0', "block_errors" integer NOT NULL DEFAULT '0', "digs" integer NOT NULL DEFAULT '0', "receptions" integer NOT NULL DEFAULT '0', "reception_errors" integer NOT NULL DEFAULT '0', "sets_attempted" integer NOT NULL DEFAULT '0', "assists" integer NOT NULL DEFAULT '0', "setting_errors" integer NOT NULL DEFAULT '0', "serve_percentage" numeric(5,2) NOT NULL DEFAULT '0', "attack_percentage" numeric(5,2) NOT NULL DEFAULT '0', "reception_percentage" numeric(5,2) NOT NULL DEFAULT '0', "is_current_season" boolean NOT NULL DEFAULT true, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cf67133c0186d897a1f5c2b906a" UNIQUE ("player_id", "season", "tournament"), CONSTRAINT "PK_d940bf05b421413ae4c6bfd83bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a28ff38484f663f215ab5ff7ce" ON "tbl_player_statistics" ("tournament") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1d5e42efdf6e698510baa8ca8" ON "tbl_player_statistics" ("season") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0e0df2572d29de6d85b73d8c6" ON "tbl_player_statistics" ("player_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_tournaments" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "description" text, "type" character varying(20) NOT NULL, "level" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'draft', "max_teams" integer NOT NULL, "registration_fee" numeric(10,2), "prize_money" numeric(12,2), "venue" character varying(200), "start_date" date NOT NULL, "end_date" date NOT NULL, "registration_start_date" date NOT NULL, "registration_end_date" date NOT NULL, "contact_email" character varying(150), "contact_phone" character varying(15), "rules" text, "requirements" text, "banner_image_url" character varying(500), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e71352c9e2bdcc8273516cdee44" UNIQUE ("code"), CONSTRAINT "PK_4675a294d8621403e91430f0ca2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e0a7ce94c8aefd2c7a9b6561f" ON "tbl_tournaments" ("start_date", "end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1f1ec4a7176b61ef930de7370" ON "tbl_tournaments" ("name") `);
        await queryRunner.query(`CREATE TABLE "tbl_tournament_squad_members" ("id" SERIAL NOT NULL, "tournament_squad_id" integer NOT NULL, "player_id" integer NOT NULL, "jersey_number" integer NOT NULL, "position" character varying(30), "is_captain" boolean NOT NULL DEFAULT false, "is_vice_captain" boolean NOT NULL DEFAULT false, "is_starting_lineup" boolean NOT NULL DEFAULT false, "status" character varying(20) NOT NULL DEFAULT 'active', "registration_date" TIMESTAMP NOT NULL DEFAULT now(), "notes" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7791ffb870ecadbf342fe26016d" UNIQUE ("tournament_squad_id", "jersey_number"), CONSTRAINT "UQ_06513cb8f8eed9a9c6378c27748" UNIQUE ("tournament_squad_id", "player_id"), CONSTRAINT "PK_147609c77081e5642732cfb8a36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_69158378ad7aee2be6c151497c" ON "tbl_tournament_squad_members" ("player_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c274b557638125ab2024bcd6e" ON "tbl_tournament_squad_members" ("tournament_squad_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_tournament_squads" ("id" SERIAL NOT NULL, "tournament_id" integer NOT NULL, "team_id" integer NOT NULL, "squad_name" character varying(100), "registration_date" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(20) NOT NULL DEFAULT 'registered', "seed_number" integer, "group_assignment" character varying(10), "total_players" integer NOT NULL DEFAULT '0', "captain_id" integer, "coach_id" integer, "notes" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bb759f17af23e58ae0a5afbf4b6" UNIQUE ("tournament_id", "team_id"), CONSTRAINT "PK_b25273a44347ba5e8df5c14630d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4b4715424bc7b8e28971421eac" ON "tbl_tournament_squads" ("team_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_55e521b0df0e78b7fa2ba0c25a" ON "tbl_tournament_squads" ("tournament_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_matches" ("id" SERIAL NOT NULL, "tournament_id" integer NOT NULL, "home_team_id" integer NOT NULL, "away_team_id" integer NOT NULL, "match_code" character varying(20) NOT NULL, "match_date" TIMESTAMP NOT NULL, "venue" character varying(200), "status" character varying(20) NOT NULL DEFAULT 'scheduled', "home_team_score" integer NOT NULL DEFAULT '0', "away_team_score" integer NOT NULL DEFAULT '0', "total_sets" integer NOT NULL DEFAULT '0', "winner_team_id" integer, "match_duration" integer, "referee_id" integer, "assistant_referee_id" integer, "match_notes" text, "weather_condition" character varying(50), "attendance" integer, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_682beeda14073d8fb2ce02ac203" UNIQUE ("match_code"), CONSTRAINT "PK_755838c1486369e177f26c01a95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7a3b10b36415c1be21adfbc74" ON "tbl_matches" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_49e6a87b00016ff4910e7bb500" ON "tbl_matches" ("match_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f88d73f72b7bf206d677ea2073" ON "tbl_matches" ("home_team_id", "away_team_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_15a15c4b43f9191e0ecdcd8d13" ON "tbl_matches" ("tournament_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_match_player_stats" ("id" SERIAL NOT NULL, "match_id" integer NOT NULL, "player_id" integer NOT NULL, "jersey_number" integer, "position_played" character varying(30), "minutes_played" integer NOT NULL DEFAULT '0', "serves_attempted" integer NOT NULL DEFAULT '0', "serves_successful" integer NOT NULL DEFAULT '0', "aces" integer NOT NULL DEFAULT '0', "service_errors" integer NOT NULL DEFAULT '0', "attacks_attempted" integer NOT NULL DEFAULT '0', "attacks_successful" integer NOT NULL DEFAULT '0', "attack_errors" integer NOT NULL DEFAULT '0', "kills" integer NOT NULL DEFAULT '0', "blocks_attempted" integer NOT NULL DEFAULT '0', "blocks_successful" integer NOT NULL DEFAULT '0', "block_assists" integer NOT NULL DEFAULT '0', "digs" integer NOT NULL DEFAULT '0', "receptions" integer NOT NULL DEFAULT '0', "reception_errors" integer NOT NULL DEFAULT '0', "sets" integer NOT NULL DEFAULT '0', "assists" integer NOT NULL DEFAULT '0', "setting_errors" integer NOT NULL DEFAULT '0', "total_points" integer NOT NULL DEFAULT '0', "yellow_cards" integer NOT NULL DEFAULT '0', "red_cards" integer NOT NULL DEFAULT '0', "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1f59fc99d309fcb86942f7a4cfd" UNIQUE ("match_id", "player_id"), CONSTRAINT "PK_933ed9adf7b9ddda1a3689c0d15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d0f3b494686fff06d766fdd205" ON "tbl_match_player_stats" ("player_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cb5b6047c4bba707aebad0f74" ON "tbl_match_player_stats" ("match_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_registration_applications" ("id" SERIAL NOT NULL, "tournament_id" integer NOT NULL, "team_id" integer NOT NULL, "applicant_id" integer NOT NULL, "application_code" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "application_fee" numeric(10,2), "payment_status" character varying(20) NOT NULL DEFAULT 'unpaid', "payment_date" TIMESTAMP, "payment_method" character varying(50), "payment_reference" character varying(100), "team_roster" jsonb, "additional_info" text, "reviewed_by" integer, "reviewed_at" TIMESTAMP, "review_notes" text, "rejection_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0cbcc12e274b402cb3c1afe0823" UNIQUE ("application_code"), CONSTRAINT "PK_496c51aeb273c536ce37aeefc63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_36ac63f33d668af60548c33ddb" ON "tbl_registration_applications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b7a5069838ab78e8e3b7854e6" ON "tbl_registration_applications" ("applicant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_437e8bc05ff4bc9a0ea47bac8f" ON "tbl_registration_applications" ("team_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d54354e4a430687f7536b897a2" ON "tbl_registration_applications" ("tournament_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_application_evaluations" ("id" SERIAL NOT NULL, "application_id" integer NOT NULL, "evaluator_id" integer NOT NULL, "evaluation_score" numeric(5,2), "criteria_scores" jsonb, "comments" text, "strengths" text, "weaknesses" text, "recommendation" character varying(20) NOT NULL, "conditional_requirements" text, "evaluation_date" TIMESTAMP NOT NULL DEFAULT now(), "is_final" boolean NOT NULL DEFAULT false, "evaluation_weight" numeric(3,2) NOT NULL DEFAULT '1', "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_32e46efcc336dad22a9f57af1d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a094db44f73e85230b9d14b06e" ON "tbl_application_evaluations" ("evaluation_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_0746a8caf398ea1accb0b7b1da" ON "tbl_application_evaluations" ("evaluator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5325dc7fbd691d719012e92e20" ON "tbl_application_evaluations" ("application_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_media_files" ("id" SERIAL NOT NULL, "filename" character varying(255) NOT NULL, "original_name" character varying(255) NOT NULL, "file_path" character varying(500) NOT NULL, "file_url" character varying(500) NOT NULL, "mime_type" character varying(100) NOT NULL, "file_size" bigint NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" integer NOT NULL, "media_type" character varying(20) NOT NULL, "media_category" character varying(50), "is_primary" boolean NOT NULL DEFAULT false, "is_public" boolean NOT NULL DEFAULT true, "uploaded_by" integer NOT NULL, "description" text, "metadata" jsonb, "alt_text" character varying(255), "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b05d38b8458cde101bfdf78cc49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1daabf8ae379c7cec6a541ad7" ON "tbl_media_files" ("is_primary") `);
        await queryRunner.query(`CREATE INDEX "IDX_b19f6a8bfc39c8b8cd6567fa9c" ON "tbl_media_files" ("media_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c720a0bef946c1b95fc8d5d2f" ON "tbl_media_files" ("uploaded_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea2ac3ce4c0e6d9853f2588222" ON "tbl_media_files" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_news_articles" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(500) NOT NULL, "excerpt" text, "content" text NOT NULL, "featured_image_url" character varying(500), "author_id" integer NOT NULL, "category" character varying(50) NOT NULL, "tags" text array, "view_count" integer NOT NULL DEFAULT '0', "like_count" integer NOT NULL DEFAULT '0', "comment_count" integer NOT NULL DEFAULT '0', "is_published" boolean NOT NULL DEFAULT false, "is_featured" boolean NOT NULL DEFAULT false, "is_pinned" boolean NOT NULL DEFAULT false, "published_at" TIMESTAMP, "scheduled_at" TIMESTAMP, "meta_title" character varying(255), "meta_description" character varying(500), "entity_type" character varying(50), "entity_id" integer, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_44b904abdbc1b87eabe9602e081" UNIQUE ("slug"), CONSTRAINT "PK_48f8c27cd620bd33afa55e359a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c4bb3d671fcf8cd45e50c2265" ON "tbl_news_articles" ("published_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5eabd2bcf2f07c78670cd26a07" ON "tbl_news_articles" ("is_published") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffbe5d69fde7522c60c67cb88f" ON "tbl_news_articles" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccf8bb15780b0f38ef217c16ad" ON "tbl_news_articles" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4816e379fc50a7ba44799a2d82" ON "tbl_news_articles" ("title") `);
        await queryRunner.query(`CREATE TABLE "tbl_system_settings" ("id" SERIAL NOT NULL, "setting_key" character varying(100) NOT NULL, "setting_value" text, "category" character varying(50) NOT NULL, "label" character varying(100), "description" text, "data_type" character varying(20) NOT NULL DEFAULT 'string', "default_value" text, "is_editable" boolean NOT NULL DEFAULT true, "is_system" boolean NOT NULL DEFAULT false, "validation_rules" jsonb, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_17c2041d83785f7c496db714f0b" UNIQUE ("setting_key"), CONSTRAINT "PK_997ccbf96e655134969bb3391a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb5260ae1903f870d9fdd6eec6" ON "tbl_system_settings" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_17c2041d83785f7c496db714f0" ON "tbl_system_settings" ("setting_key") `);
        await queryRunner.query(`CREATE TABLE "tbl_activity_logs" ("id" SERIAL NOT NULL, "user_id" integer, "action_type" character varying(50) NOT NULL, "entity_type" character varying(50), "entity_id" integer, "old_values" jsonb, "new_values" jsonb, "ip_address" character varying(45), "user_agent" text, "session_id" character varying(255), "description" text, "severity_level" character varying(20) NOT NULL DEFAULT 'info', "is_successful" boolean NOT NULL DEFAULT true, "error_message" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7e14060216563a64ab9419fefc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70a4a5cab1086b08202b361aa6" ON "tbl_activity_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_98b65d6ed5c439e3d1573840d7" ON "tbl_activity_logs" ("action_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c7be72fdf9dbd929747edf8bd" ON "tbl_activity_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_daeba2eb5132aec634fd0a41ce" ON "tbl_activity_logs" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "tbl_notifications" ("id" SERIAL NOT NULL, "recipient_id" integer NOT NULL, "sender_id" integer, "notification_type" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "action_url" character varying(500), "entity_type" character varying(50), "entity_id" integer, "metadata" jsonb, "priority" character varying(20) NOT NULL DEFAULT 'normal', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "is_sent" boolean NOT NULL DEFAULT false, "sent_at" TIMESTAMP, "expires_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_864f5e52afeed73fdfd87ba738b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aeb3a44c4081f10a18d23db0c1" ON "tbl_notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c07fcb7b4d786608786e5a1d0" ON "tbl_notifications" ("notification_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_6247d696bfc536d2731cdd9862" ON "tbl_notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d344f0bb13fe209aa352d40a9" ON "tbl_notifications" ("recipient_id") `);
        await queryRunner.query(`ALTER TABLE "tbl_user_profiles" ADD CONSTRAINT "FK_5d9c02e75b2b8b22c9708ae5590" FOREIGN KEY ("user_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_players" ADD CONSTRAINT "FK_cf55e3017ab32f2dbf438e0b3dc" FOREIGN KEY ("user_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_teams" ADD CONSTRAINT "FK_bb2b45887926dddc95622d83764" FOREIGN KEY ("division_id") REFERENCES "tbl_divisions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_teams" ADD CONSTRAINT "FK_5bc92dbef3316b73a33f6cc852c" FOREIGN KEY ("coach_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_teams" ADD CONSTRAINT "FK_9bcfd6c5044351f4adb9d62ce16" FOREIGN KEY ("assistant_coach_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_team_stats" ADD CONSTRAINT "FK_fee0b5954caea0f19ad63ef24d7" FOREIGN KEY ("team_id") REFERENCES "tbl_teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_team_members" ADD CONSTRAINT "FK_faead59db8023099d9d0046249a" FOREIGN KEY ("team_id") REFERENCES "tbl_teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_team_members" ADD CONSTRAINT "FK_1689d4b0d6dcbc5ae5fe2413c96" FOREIGN KEY ("player_id") REFERENCES "tbl_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_player_statistics" ADD CONSTRAINT "FK_d0e0df2572d29de6d85b73d8c6c" FOREIGN KEY ("player_id") REFERENCES "tbl_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squad_members" ADD CONSTRAINT "FK_5c274b557638125ab2024bcd6e2" FOREIGN KEY ("tournament_squad_id") REFERENCES "tbl_tournament_squads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squad_members" ADD CONSTRAINT "FK_69158378ad7aee2be6c151497c6" FOREIGN KEY ("player_id") REFERENCES "tbl_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squads" ADD CONSTRAINT "FK_55e521b0df0e78b7fa2ba0c25a8" FOREIGN KEY ("tournament_id") REFERENCES "tbl_tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squads" ADD CONSTRAINT "FK_4b4715424bc7b8e28971421eac3" FOREIGN KEY ("team_id") REFERENCES "tbl_teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" ADD CONSTRAINT "FK_15a15c4b43f9191e0ecdcd8d13d" FOREIGN KEY ("tournament_id") REFERENCES "tbl_tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" ADD CONSTRAINT "FK_5bcf14c8e083c3aac88c5b82444" FOREIGN KEY ("home_team_id") REFERENCES "tbl_teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" ADD CONSTRAINT "FK_618ee1456f28fa0c5b7a1d73a22" FOREIGN KEY ("away_team_id") REFERENCES "tbl_teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" ADD CONSTRAINT "FK_aeeadcbe4a286814232be664f5c" FOREIGN KEY ("winner_team_id") REFERENCES "tbl_teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" ADD CONSTRAINT "FK_40506e30d34e940220eb5427144" FOREIGN KEY ("referee_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" ADD CONSTRAINT "FK_0e91d655acc92b82c7903fb314c" FOREIGN KEY ("assistant_referee_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_match_player_stats" ADD CONSTRAINT "FK_0cb5b6047c4bba707aebad0f745" FOREIGN KEY ("match_id") REFERENCES "tbl_matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_match_player_stats" ADD CONSTRAINT "FK_d0f3b494686fff06d766fdd2050" FOREIGN KEY ("player_id") REFERENCES "tbl_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" ADD CONSTRAINT "FK_d54354e4a430687f7536b897a21" FOREIGN KEY ("tournament_id") REFERENCES "tbl_tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" ADD CONSTRAINT "FK_437e8bc05ff4bc9a0ea47bac8fa" FOREIGN KEY ("team_id") REFERENCES "tbl_teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" ADD CONSTRAINT "FK_2b7a5069838ab78e8e3b7854e69" FOREIGN KEY ("applicant_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" ADD CONSTRAINT "FK_80982d2c61c62b5c750c367e865" FOREIGN KEY ("reviewed_by") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_application_evaluations" ADD CONSTRAINT "FK_5325dc7fbd691d719012e92e205" FOREIGN KEY ("application_id") REFERENCES "tbl_registration_applications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_application_evaluations" ADD CONSTRAINT "FK_0746a8caf398ea1accb0b7b1dad" FOREIGN KEY ("evaluator_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_media_files" ADD CONSTRAINT "FK_7c720a0bef946c1b95fc8d5d2fd" FOREIGN KEY ("uploaded_by") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_news_articles" ADD CONSTRAINT "FK_ccf8bb15780b0f38ef217c16ad2" FOREIGN KEY ("author_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_notifications" ADD CONSTRAINT "FK_2d344f0bb13fe209aa352d40a9d" FOREIGN KEY ("recipient_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tbl_notifications" ADD CONSTRAINT "FK_650e7f393a8fb582f6eb4a78f62" FOREIGN KEY ("sender_id") REFERENCES "tbl_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tbl_notifications" DROP CONSTRAINT "FK_650e7f393a8fb582f6eb4a78f62"`);
        await queryRunner.query(`ALTER TABLE "tbl_notifications" DROP CONSTRAINT "FK_2d344f0bb13fe209aa352d40a9d"`);
        await queryRunner.query(`ALTER TABLE "tbl_news_articles" DROP CONSTRAINT "FK_ccf8bb15780b0f38ef217c16ad2"`);
        await queryRunner.query(`ALTER TABLE "tbl_media_files" DROP CONSTRAINT "FK_7c720a0bef946c1b95fc8d5d2fd"`);
        await queryRunner.query(`ALTER TABLE "tbl_application_evaluations" DROP CONSTRAINT "FK_0746a8caf398ea1accb0b7b1dad"`);
        await queryRunner.query(`ALTER TABLE "tbl_application_evaluations" DROP CONSTRAINT "FK_5325dc7fbd691d719012e92e205"`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" DROP CONSTRAINT "FK_80982d2c61c62b5c750c367e865"`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" DROP CONSTRAINT "FK_2b7a5069838ab78e8e3b7854e69"`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" DROP CONSTRAINT "FK_437e8bc05ff4bc9a0ea47bac8fa"`);
        await queryRunner.query(`ALTER TABLE "tbl_registration_applications" DROP CONSTRAINT "FK_d54354e4a430687f7536b897a21"`);
        await queryRunner.query(`ALTER TABLE "tbl_match_player_stats" DROP CONSTRAINT "FK_d0f3b494686fff06d766fdd2050"`);
        await queryRunner.query(`ALTER TABLE "tbl_match_player_stats" DROP CONSTRAINT "FK_0cb5b6047c4bba707aebad0f745"`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" DROP CONSTRAINT "FK_0e91d655acc92b82c7903fb314c"`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" DROP CONSTRAINT "FK_40506e30d34e940220eb5427144"`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" DROP CONSTRAINT "FK_aeeadcbe4a286814232be664f5c"`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" DROP CONSTRAINT "FK_618ee1456f28fa0c5b7a1d73a22"`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" DROP CONSTRAINT "FK_5bcf14c8e083c3aac88c5b82444"`);
        await queryRunner.query(`ALTER TABLE "tbl_matches" DROP CONSTRAINT "FK_15a15c4b43f9191e0ecdcd8d13d"`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squads" DROP CONSTRAINT "FK_4b4715424bc7b8e28971421eac3"`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squads" DROP CONSTRAINT "FK_55e521b0df0e78b7fa2ba0c25a8"`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squad_members" DROP CONSTRAINT "FK_69158378ad7aee2be6c151497c6"`);
        await queryRunner.query(`ALTER TABLE "tbl_tournament_squad_members" DROP CONSTRAINT "FK_5c274b557638125ab2024bcd6e2"`);
        await queryRunner.query(`ALTER TABLE "tbl_player_statistics" DROP CONSTRAINT "FK_d0e0df2572d29de6d85b73d8c6c"`);
        await queryRunner.query(`ALTER TABLE "tbl_team_members" DROP CONSTRAINT "FK_1689d4b0d6dcbc5ae5fe2413c96"`);
        await queryRunner.query(`ALTER TABLE "tbl_team_members" DROP CONSTRAINT "FK_faead59db8023099d9d0046249a"`);
        await queryRunner.query(`ALTER TABLE "tbl_team_stats" DROP CONSTRAINT "FK_fee0b5954caea0f19ad63ef24d7"`);
        await queryRunner.query(`ALTER TABLE "tbl_teams" DROP CONSTRAINT "FK_9bcfd6c5044351f4adb9d62ce16"`);
        await queryRunner.query(`ALTER TABLE "tbl_teams" DROP CONSTRAINT "FK_5bc92dbef3316b73a33f6cc852c"`);
        await queryRunner.query(`ALTER TABLE "tbl_teams" DROP CONSTRAINT "FK_bb2b45887926dddc95622d83764"`);
        await queryRunner.query(`ALTER TABLE "tbl_players" DROP CONSTRAINT "FK_cf55e3017ab32f2dbf438e0b3dc"`);
        await queryRunner.query(`ALTER TABLE "tbl_user_profiles" DROP CONSTRAINT "FK_5d9c02e75b2b8b22c9708ae5590"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d344f0bb13fe209aa352d40a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6247d696bfc536d2731cdd9862"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c07fcb7b4d786608786e5a1d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aeb3a44c4081f10a18d23db0c1"`);
        await queryRunner.query(`DROP TABLE "tbl_notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_daeba2eb5132aec634fd0a41ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c7be72fdf9dbd929747edf8bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98b65d6ed5c439e3d1573840d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70a4a5cab1086b08202b361aa6"`);
        await queryRunner.query(`DROP TABLE "tbl_activity_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17c2041d83785f7c496db714f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb5260ae1903f870d9fdd6eec6"`);
        await queryRunner.query(`DROP TABLE "tbl_system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4816e379fc50a7ba44799a2d82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccf8bb15780b0f38ef217c16ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffbe5d69fde7522c60c67cb88f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5eabd2bcf2f07c78670cd26a07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c4bb3d671fcf8cd45e50c2265"`);
        await queryRunner.query(`DROP TABLE "tbl_news_articles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea2ac3ce4c0e6d9853f2588222"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c720a0bef946c1b95fc8d5d2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b19f6a8bfc39c8b8cd6567fa9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1daabf8ae379c7cec6a541ad7"`);
        await queryRunner.query(`DROP TABLE "tbl_media_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5325dc7fbd691d719012e92e20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0746a8caf398ea1accb0b7b1da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a094db44f73e85230b9d14b06e"`);
        await queryRunner.query(`DROP TABLE "tbl_application_evaluations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d54354e4a430687f7536b897a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_437e8bc05ff4bc9a0ea47bac8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b7a5069838ab78e8e3b7854e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36ac63f33d668af60548c33ddb"`);
        await queryRunner.query(`DROP TABLE "tbl_registration_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cb5b6047c4bba707aebad0f74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0f3b494686fff06d766fdd205"`);
        await queryRunner.query(`DROP TABLE "tbl_match_player_stats"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15a15c4b43f9191e0ecdcd8d13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f88d73f72b7bf206d677ea2073"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49e6a87b00016ff4910e7bb500"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7a3b10b36415c1be21adfbc74"`);
        await queryRunner.query(`DROP TABLE "tbl_matches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55e521b0df0e78b7fa2ba0c25a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b4715424bc7b8e28971421eac"`);
        await queryRunner.query(`DROP TABLE "tbl_tournament_squads"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c274b557638125ab2024bcd6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69158378ad7aee2be6c151497c"`);
        await queryRunner.query(`DROP TABLE "tbl_tournament_squad_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1f1ec4a7176b61ef930de7370"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e0a7ce94c8aefd2c7a9b6561f"`);
        await queryRunner.query(`DROP TABLE "tbl_tournaments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0e0df2572d29de6d85b73d8c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1d5e42efdf6e698510baa8ca8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a28ff38484f663f215ab5ff7ce"`);
        await queryRunner.query(`DROP TABLE "tbl_player_statistics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faead59db8023099d9d0046249"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1689d4b0d6dcbc5ae5fe2413c9"`);
        await queryRunner.query(`DROP TABLE "tbl_team_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fee0b5954caea0f19ad63ef24d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62a6114da9c78a55fc620da2c1"`);
        await queryRunner.query(`DROP TABLE "tbl_team_stats"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aac77fb1de4d7063c45934d922"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb2b45887926dddc95622d8376"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b40662ac94791561ce5f411e06"`);
        await queryRunner.query(`DROP TABLE "tbl_teams"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee1c4de334a95fc856c0daf615"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8003b55efcb85e34f9f06bcdb"`);
        await queryRunner.query(`DROP TABLE "tbl_divisions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22e9c745c648bad6b39c5d5b58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d74ab662f9d3964f78b3416d5d"`);
        await queryRunner.query(`DROP TABLE "tbl_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d505b968f838bbb3e6230caf56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dae2eefae9e71064fa8fe1ba3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf55e3017ab32f2dbf438e0b3d"`);
        await queryRunner.query(`DROP TABLE "tbl_players"`);
        await queryRunner.query(`DROP TABLE "tbl_user_profiles"`);
    }

}
